language: objective-c

branches:
 only:
 - master

xcode_scheme: iOS Example
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

script:
- xcodebuild clean build test -workspace JustJson.xcworkspace -scheme "iOS Example"
